### ISSUE TITLE
Upstream not tracked

### ISSUE THREAD

**Issue by madebr** [chromium/pdfium#2]
Hello,

This gihub clone does not track the git repo at https://pdfium.googlesource.com/pdfium/.
The last commit on this fork is dated *May 13, 2020*, whereas the last commit on google git is *July 23, 2021*.
The delta is currently 14 months, and counting.

It would be nice if this repo would track upstream once again.

Thanks

**Comment by mara004** [comment]
Seems to be fixed now. The repository is up-to-date and mirros `https://pdfium.googlesource.com/pdfium/` correctly.

**Comment by madebr** [comment]
Weird, I received a mail notification just today.
3 months after you posted this message.
